colorScheme = "slate"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["posts"]
firebase = {}
fathomAnalytics = {}
verification = {}
highlightCurrentMenuArea = ""

[header]
layout = "basic"

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile"
showRecent = true
showRecentItems = 2
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false

[article]
showDate = true
showDateUpdated = false
showAuthor = true
showHero = false
heroStyle = "basic"
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editAppendPath = true
editURL = "https://github.com/UZPENG/Blog/edit/main/content/zh-cn"
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showSummary = false
sharingLinks = [
  "linkedin",
  "twitter",
  "whatsapp",
  "pinterest",
  "reddit",
  "facebook",
  "email",
]

[list]
showBreadcrumbs = false
showSummary = false
showTableOfContents = false
showCards = false
groupByYear = true
cardView = false
cardViewScreenWidth = false
constrainItemsWidth = true

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true

[repo]
  url = "https://github.com/UZPENG/Blog"
  branch = "main"
  editBranch = "main"
  contentFolder = "content"